### ISSUE TITLE
"lx logical matrix"

### ISSUE THREAD

**Issue by Magalame** [quantumgizmos/bp_osd#4]
Hi!

I've been looking through the readme, and something puzzles me. I'd have expected to provide Hx and Hz to the decoder, however it asks instead for Hx and Lx the "logical matrix". I looked through the paper attached to this repo, but couldn't find a description of what is meant by the logical matrix. 

Shortly put, how can I go from Hz to Lx? 

Thanks!

**Comment by quantumgizmos** [comment]
Hi.

We're assuming that the codes we are decoding are CSS and are subject to an error model in which X- and Z-errors are independent of one another. In this setting we, we can treat the X and Z components of the code as two independent decoding problems. eg, we have one decoding problem to detect X-errors and another to detect Z-errors. Because the codes we considered in the paper were constructed using the symmetric hypergraph product, it sufficed to run numerics on just one of the error types to assess the code performance. We chose to do this with the H_X matrix, but our simulation should work (without modification) for the H_Z too. 

The logical matrix is a matrix in which row is a logical operator of the code. So the L_X logical matrix is a matrix formed by stacking the X-logical operators on top of one another. Likewise the L_Z logical matrix is the matrix formed by stacking the L_Z logical operators on top of one another.

The reason we need the logical matrix is determine whether the output of the BP+OSD decoder results in a logical error. We can find the L_X logical operators by looking for vectors g that satisfy the following conditions:

1. g \in KER(H_Z)
2.  g \notin ROWSPACE(H_X)

In the above, condition 1 ensures that the logical operators commute with all the stabilizers. Condition 2 ensures the logical operator is not itself a stabilizer.

Similarly, you can calculate the L_Z logical operators by looking for vectors g that satisfy:

1. g \in KER(H_X)
2. g \notin ROWSPACE(H_Z)

What types of codes are you looking to decode? In general, finding the logical operators of a CSS code is computationally difficult. However, if the codes you are using are constructed using the hypergraph product there are techniques that can be used to simplify the search.

Joschka

**Comment by Magalame** [comment]
Hi! 

Thanks for the help! I'm trying to simulate bicycle codes and hypergraph product codes. Do you know of an efficient process do get L_X/L_Z for these?

**Comment by Magalame** [comment]
I looked at the `bp_osd_decode.cpp` script, if I understand correctly, L_X/L_Z are used to make sure the decoding process didn't "jump" by a logical error.

If I'm not mistaken, it should be equivalent to this:
- generate random Z error represented by binary vector e
- BP+OSD gives us a guess e'
- if e + e' =/= 0, check if there exist a solution to (e+e')=w*H_Z for some w, if there is, then we have successfully recovered from the error

This would eliminate the need for L_X/L_Z, am I missing something?

**Comment by Magalame** [comment]
I took a look at the simulation script, it seems like L_X/L_Z are used to verify that the decoding process didn't "jump" by an error.

If I'm not mistaken, it would be equivalent to the following (assume `e` is a Z error, and `e'` is the guess output from BP)
- check if `e+e' ≡ f = 0`
- if not, what we want to know if there exist a solution to the system `f = w*H_Z' for some vector `w`
- this is equivalent to the system `H_Z^T*w^T=f^T`, which has no solution if `rank(H^T|f^T) > rank(H^T)`

if I'm not mistaken, it is computationally efficient, correct, and eliminates the need for L_X/L_Z

**Comment by quantumgizmos** [comment]
Hi. I think you're approach is valid and will give the correct numerics. If you implement it, could you test it on the code given in the example script and report back on whether it works?

**Comment by quantumgizmos** [comment]
For the L_X/L_Z operators of a hypergraph product code:

1) L_X operators are vectors with the form:

 t \notin ROWSPACE(H_1)\otimes j\in KER(H_2) \ | \ h \in KER(H_1^T) \otimes s \notin ROWSPACE(H_2^T)

2) L_Z operators are vectors of the form:

j\in KER(H_1) \otimes t \notin ROWSPACE(H_2) \ | \ s \notin ROWSPACE(H_1^T)  \otimes h \in KER(H_2^T)

**Comment by Magalame** [comment]
I implemented it, and it gives the correct numerics, however there is a runtime increase:
- hgp_mkmn_16_4_6 jumps from 1s to 6s
- hgp_mkmn_24_6_10 jumps from 6s to 24s

maybe it'd be appropriate to add an option to switch between lx check/hz check?

**Comment by quantumgizmos** [comment]
Brilliant! This will be useful for QLDPC codes where there is no obvious way of finding the L_X/L_Z logical matrices.

The run-time increase is likely due to the increased complexity of calculating the rank (gaussian elimination) relative to the other method that is just matrix-vector multiplication.

An option to switch between the two methods would be good. I'll implement it sometime this week. Alternatively, if you've already got a working version submit a pull request and I'll merge.

**Comment by Magalame** [comment]
I'll clean it up and then submit :)

**Comment by quantumgizmos** [comment]
Issue resolved with pr #5
