### ISSUE TITLE
Memory leak with the hz logical check method

### ISSUE THREAD

**Issue by Magalame** [quantumgizmos/bp_osd#6]
Hi again!

It seems like there is a memory leak, as a simulation of a simple 400 qubits code is currently taking up 4GB of RAM on my laptop. I'll look into it. I haven't tried the lx method so I can't say yet whether it is hz-specific or not

**Comment by quantumgizmos** [comment]
Hi.

It looks like the problem was mostly due to me using the c "free" method to clear a mod2sparse matrix in the rank calculation function. I changed it to "mod2sparse_free" and the situation is much improved. However, there still seems to be a memory leak at rate of about 1mb/1000 cycles. I will try and pinpoint the cause of this.

**Comment by quantumgizmos** [comment]
I've investigated a little further and it seems as though the problem is present for the "lx" decoding as well, although not quite as severe as in the "hz" case. I think the reason must be that the mod2sparse_free function doesn't clear everything, leaving a bit of residual memory that accumulates as the simulation progresses. As the "hz" method generates-then-deletes  two new matrices after each cycle, this builds up comparatively quickly. For the "lx" method, we see less of a problem, as matrices are only generated when the OSD routine is called.

**Comment by Magalame** [comment]
Thanka for the quick response!
I think maybe a solution for hz check is to allocate the matrices in the simulation script itself, and pass them as arguments to the check function? That way we only need to allocate/free once

**Comment by quantumgizmos** [comment]
That should work. Another thing you could do is pre-compute the rank(H^T) to avoid having to recalculate it every cycle. If you implement this, could you submit another PR?
